Added 5.3. Select proper Xcode version.

diff --git a/.github/workflows/Tests.yml b/.github/workflows/Tests.yml
--- a/.github/workflows/Tests.yml
+++ b/.github/workflows/Tests.yml
@@ -1,5 +1,5 @@
 # --------------------------------------------------------------------------------
-# This workflow was automatically generated by Action Status 1.0.1 (230).
+# This workflow was automatically generated by Action Status 1.0.2 (245).
 # (see https://actionstatus.elegantchaos.com for more details)
 # --------------------------------------------------------------------------------
 
@@ -11,7 +11,7 @@ jobs:
 
     linux-swift-51:
         name: Linux (Swift 5.1)
-        runs-on: ubuntu-latest
+        runs-on: ubuntu-18.04
         container: swift:5.1
         steps:
         - name: Checkout
@@ -26,6 +26,7 @@ jobs:
           run: swift test --configuration release -Xswiftc -enable-testing 
         - name: Upload Logs
           uses: actions/upload-artifact@v1
+          if: always()
           with:
             name: logs
             path: logs
@@ -40,9 +41,9 @@ jobs:
 
 
     linux-swift-52:
-        name: Linux (Swift 5.2 Nightly)
-        runs-on: ubuntu-latest
-        container: swiftlang/swift:nightly-5.2
+        name: Linux (Swift 5.2)
+        runs-on: ubuntu-18.04
+        container: swift:5.2.3-bionic
         steps:
         - name: Checkout
           uses: actions/checkout@v1
@@ -56,6 +57,7 @@ jobs:
           run: swift test --configuration release -Xswiftc -enable-testing --enable-test-discovery
         - name: Upload Logs
           uses: actions/upload-artifact@v1
+          if: always()
           with:
             name: logs
             path: logs
@@ -64,14 +66,45 @@ jobs:
           if: always()
           with:
             type: ${{ job.status }}
-            job_name: 'Linux (Swift 5.2 Nightly)'
+            job_name: 'Linux (Swift 5.2)'
+            mention_if: 'failure'
+            url: ${{ secrets.SLACK_WEBHOOK }}
+
+
+    linux-swift-53:
+        name: Linux (Swift 5.3 Nightly)
+        runs-on: ubuntu-18.04
+        container: swiftlang/swift:nightly-5.3-bionic
+        steps:
+        - name: Checkout
+          uses: actions/checkout@v1
+        - name: Swift Version
+          run: swift --version
+        - name: Make Logs Directory
+          run: mkdir logs
+        - name: Build (Release)
+          run: swift build -c release
+        - name: Test (Release)
+          run: swift test --configuration release -Xswiftc -enable-testing --enable-test-discovery
+        - name: Upload Logs
+          uses: actions/upload-artifact@v1
+          if: always()
+          with:
+            name: logs
+            path: logs
+        - name: Slack Notification
+          uses: elegantchaos/slatify@master
+          if: always()
+          with:
+            type: ${{ job.status }}
+            job_name: 'Linux (Swift 5.3 Nightly)'
             mention_if: 'failure'
             url: ${{ secrets.SLACK_WEBHOOK }}
 
 
     linux-swift-nightly:
         name: Linux (Swift Development Nightly)
-        runs-on: ubuntu-latest
+        runs-on: ubuntu-18.04
         container: swiftlang/swift:nightly
         steps:
         - name: Checkout
@@ -86,6 +119,7 @@ jobs:
           run: swift test --configuration release -Xswiftc -enable-testing --enable-test-discovery
         - name: Upload Logs
           uses: actions/upload-artifact@v1
+          if: always()
           with:
             name: logs
             path: logs
@@ -109,6 +143,11 @@ jobs:
           run: swift --version
         - name: Make Logs Directory
           run: mkdir logs
+        - name: Set Xcode Version
+          run: |
+            xcode-select -s /Applications/Xcode_11.3.1.app
+            swift --version
+            xcodebuild --version
         - name: Xcode Version
           run: xcodebuild -version
         - name: XC Pretty
@@ -142,6 +181,7 @@ jobs:
             xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME"  -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-macOS-xcode-test-release.log | xcpretty
         - name: Upload Logs
           uses: actions/upload-artifact@v1
+          if: always()
           with:
             name: logs
             path: logs
@@ -156,7 +196,69 @@ jobs:
 
 
     xcode-swift-52:
-        name: Xcode (Swift 5.2 Nightly)
+        name: Xcode (Swift 5.2)
+        runs-on: macOS-latest
+        steps:
+        - name: Checkout
+          uses: actions/checkout@v1
+        - name: Swift Version
+          run: swift --version
+        - name: Make Logs Directory
+          run: mkdir logs
+        - name: Set Xcode Version
+          run: |
+            xcode-select -s /Applications/Xcode_11.4.app
+            swift --version
+            xcodebuild --version
+        - name: Xcode Version
+          run: xcodebuild -version
+        - name: XC Pretty
+          run: sudo gem install xcpretty-travis-formatter
+        - name: Detect Workspace & Scheme (macOS)
+          run: |
+            WORKSPACE="Runner.xcworkspace"
+            if [[ ! -e "$WORKSPACE" ]]
+            then
+            WORKSPACE="."
+            GOTPACKAGE=$(xcodebuild -workspace . -list | (grep Runner-Package || true))
+            if [[ $GOTPACKAGE != "" ]]
+            then
+            SCHEME="Runner-Package"
+            else
+            SCHEME="Runner"
+            fi
+            else
+            SCHEME="Runner-macOS"
+            fi
+            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'" > setup.sh
+        - name: Build (macOS Release)
+          run: |
+            source "setup.sh"
+            echo "Building workspace $WORKSPACE scheme $SCHEME."
+            xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | tee logs/xcodebuild-macOS-xcode-build-release.log | xcpretty
+        - name: Test (macOS Release)
+          run: |
+            source "setup.sh"
+            echo "Testing workspace $WORKSPACE scheme $SCHEME."
+            xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME"  -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-macOS-xcode-test-release.log | xcpretty
+        - name: Upload Logs
+          uses: actions/upload-artifact@v1
+          if: always()
+          with:
+            name: logs
+            path: logs
+        - name: Slack Notification
+          uses: elegantchaos/slatify@master
+          if: always()
+          with:
+            type: ${{ job.status }}
+            job_name: 'Xcode (Swift 5.2)'
+            mention_if: 'failure'
+            url: ${{ secrets.SLACK_WEBHOOK }}
+
+
+    xcode-swift-53:
+        name: Xcode (Swift 5.3 Nightly)
         runs-on: macOS-latest
         steps:
         - name: Checkout
@@ -167,7 +269,7 @@ jobs:
           run: mkdir logs
         - name: Install Toolchain
           run: |
-            branch="swift-5.2-branch"
+            branch="swift-5.3-branch"
             wget --quiet https://swift.org/builds/$branch/xcode/latest-build.yml
             grep "download:" < latest-build.yml > filtered.yml
             sed -e 's/-osx.pkg//g' filtered.yml > stripped.yml
@@ -212,6 +314,7 @@ jobs:
             xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME"  -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-macOS-xcode-test-release.log | xcpretty
         - name: Upload Logs
           uses: actions/upload-artifact@v1
+          if: always()
           with:
             name: logs
             path: logs
@@ -220,7 +323,7 @@ jobs:
           if: always()
           with:
             type: ${{ job.status }}
-            job_name: 'Xcode (Swift 5.2 Nightly)'
+            job_name: 'Xcode (Swift 5.3 Nightly)'
             mention_if: 'failure'
             url: ${{ secrets.SLACK_WEBHOOK }}
 
@@ -282,6 +385,7 @@ jobs:
             xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME"  -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-macOS-xcode-test-release.log | xcpretty
         - name: Upload Logs
           uses: actions/upload-artifact@v1
+          if: always()
           with:
             name: logs
             path: logs
